theme: minima
title: Hi! How are ya?
author: Bonnie-123
email: lani09br@rams.colostate.edu
description: > # this means to ignore newlines until "baseurl:"
  I am learning to write a blog on GitHub and am very new.
  These step by step activities are extremely helpful.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
